package main

import (
	"bytes"
	"fmt"
	"os"
	"os/exec"
	"strings"
)

// Testcases are embedded directly so the verifier does not depend on external files.
var rawTestcases = []string{
	"WUBWUBBIQPWUBZJPLWUBQEWUBEYDWUB",
	"WUBJDWUBVWUBPRDWUBNKWUBTWUBRPWUBWUB",
	"WZVUWUBWUB",
	"XKWUBGWUBHZWUBWUB",
	"WUBWUBQPDWUBWUB",
	"WUBWUBZTWUBOCTWUBKSHJWUBGFWUBTWUB",
	"EBWUBWUB",
	"WUBWUBWQIQWUBGVWUBSIOPWUBCKTWUBPWUBWUB",
	"WUBAXWUBDWH",
	"WWUBUBZWUBWUB",
	"WUBMWUBLWUBBWUBGWUBWD",
	"WUBWUBRWUBWUBWUB",
	"WUBFBQOWUBTWUBWUBW",
	"WUBWUBWVWUBYBWUBFKWUBDTOWUBAPWUB",
	"WUBULMWUBERWWUBOWUWUBBKWUBR",
	"SUTWUBWWUBJWUWUBBXNUCWUBWUB",
	"WUBWUBBMWSWUBYVWBWUBOCWUBWFOWUB",
	"WUBWUBBWUBKJOBWUBGRUCWUBAMWUBKAGA",
	"WUBGWUBTWUBJIWUBDPWUBUCAI",
	"DEIWUBB",
	"WUBLSBWUBWUOUWUBLRFGWUBSJAEWUBIKWUB",
	"BWUBWUBFESWUBLWUBMRWUB",
	"WUBWUBJWUBKJNDWUBRWUBPKZZWUBDPDWUB",
	"XVEWUBUSWUBZUCC",
	"WUBWUBADMRWUB",
	"NCWUBHISWUBNGWUBDCWWUBWUB",
	"PWUWUBBIGUBWUBWUB",
	"WUBDTWUBESMUWUBQPVKWUB",
	"AKWUBKBQWUB",
	"WUBSJWWWUBCZCQ",
	"WUBWUBFZEWUBLQMQWUBSWUBVWUBWUB",
	"JRWUBPZMTWUBZAWUBXWUB",
	"CPIWUBYNMWUBBFUEWUB",
	"WUBWUBBWUBNEPTWUBV",
	"WUBWUBBTOMWUBBDPWUBYWUBWUBABWUBWUB",
	"WUBWUBZYYPWUBBWUBWUB",
	"VWUBZEMWUBXVZWUBWUB",
	"WUBZWUBOLYGWUB",
	"WUBBWUB",
	"WUBHCWUBQJDEWUBSNCDWUBCDNYWUBXAWUB",
	"WUBWUBKXIC",
	"HWUBWUBCTE",
	"WUBWATWUBWUBEFWUBDPLW",
	"JRUWUBFSCWUBRWUBFME",
	"YFWUBLNV",
	"WUBWWUBEWUBJRNXWUBSNWUBWUB",
	"WUBULUQWUBM",
	"GLJPWUBFWUBIWUBWUB",
	"WUBWUBMFYNWUBFHOK",
	"WUBWUBYGJAWUB",
	"WUBWUBJDWUB",
	"WUBWYPCWUBYHRYWUB",
	"WUBWUBIWUB",
	"ODXIWUBJYVWUBTCWUBCWUBJRKWUBWUB",
	"WUBWUBNWUBJQEWUBWUB",
	"WUBNWUBXYZIWUBOLSWUBFDWUBMWUBWUB",
	"LUPWUBGPPWWUBPUBWUBJEXPWUBT",
	"WUBWUBQWUBVWUBVWUBALBD",
	"WUBEYWUBGDNWUBWKMFWUB",
	"WUBOWWUBQKWUBGFWUBLZMNWUB",
	"GSWBWUBBHUWUBCWUB",
	"WUBTCWWUBYLN",
	"SOPIWUBGKIBWUBBWUBLAWUBUAEWUB",
	"RHOGWUBTDTWUBZWUBKROWUBIAQ",
	"WUBGGIWUBJQMWUB",
	"WUBJWUBAWUB",
	"PWUBOOD",
	"TCNRWUBBFHP",
	"WUBKNDWUBTRZWUBWJWUBWUB",
	"WUBWUBIHAWUBTWUBFWUBHGJXWUBXWUBWUB",
	"WUBWUBMWUBWUBWUB",
	"WUBCQWUBVKHWUBWUB",
	"EZWUBRWUBLSUWUBZWUBMEWUBWUB",
	"ZYWWUBUBSYWGWUBWUB",
	"WUBWUBUPWUBTWUBQWUB",
	"WUBHWUBVPWUBRKWC",
	"ZJMWUBGWUB",
	"WUBWUBOVXWUBIL",
	"XWUBLAWUBUWUBBAH",
	"VNEWUB",
	"WUBFUKWUBMANIWUBYBSWUBWUBDWUB",
	"KWUBFH",
	"WUBWCWUBTDTUWUBWETTWUBIWUBZXX",
	"CLWUBJWUBVWUB",
	"WUBAJQJWUBBYRSWUBVBOWUBXDMWUBL",
	"WUBVYGWUBMIGWUBS",
	"WUBFEKWUBSWUBSWUBLLWUBUJKWUB",
	"WUBZWUBSB",
	"WUBWUBVVYIWUBWUBWUB",
	"WUBWUBQFWUBVWUBSDWUBWUB",
	"WUBWUBYNIJWUBANYWUBIRQWUBKGWWUBZEAY",
	"LOBRWUBUTZZWUBALWUBVGWUBUWPWUBWUB",
	"WUBIFWUBCSOHWUBQZZWWUBGWUBOCWUBWUB",
	"WUBNYYWUBTKCWUBAPA",
	"WUBYUWUBUVWUBWBSOWUBSESWUBKAMWUBWUB",
	"WUBACGWUBVWUBBKAK",
	"WUBWUBVETEWUBJQBFWUBEPWUBWUB",
	"WUBWUBRWUBWUB",
	"WUBLZWUBCWUBIGWUBKWWWUB",
	"WUBYOWUBBUWUBUQWUWUBBY",
}

// remixSong is the embedded solution from 208A.go, adapted to work on a single line.
func remixSong(input string) string {
	s := strings.TrimSpace(input)
	parts := strings.Split(s, "WUB")
	words := make([]string, 0, len(parts))
	for _, p := range parts {
		if p != "" {
			words = append(words, p)
		}
	}
	if len(words) == 0 {
		return ""
	}
	return strings.Join(words, " ")
}

func main() {
	if len(os.Args) != 2 {
		fmt.Println("usage: go run verifierA.go /path/to/binary")
		os.Exit(1)
	}
	bin := os.Args[1]
	for idx, line := range rawTestcases {
		expect := remixSong(line)
		cmd := exec.Command(bin)
		cmd.Stdin = strings.NewReader(line + "\n")
		var out bytes.Buffer
		var stderr bytes.Buffer
		cmd.Stdout = &out
		cmd.Stderr = &stderr
		err := cmd.Run()
		if err != nil {
			fmt.Printf("test %d: runtime error: %v\nstderr: %s\n", idx+1, err, stderr.String())
			os.Exit(1)
		}
		got := strings.TrimSpace(out.String())
		if got != expect {
			fmt.Printf("test %d failed\nexpected: %q\n got: %q\n", idx+1, expect, got)
			os.Exit(1)
		}
	}
	fmt.Printf("All %d tests passed\n", len(rawTestcases))
}
