package main

import (
	"bytes"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
)

func buildOracle() (string, error) {
	dir, err := os.Getwd()
	if err != nil {
		return "", err
	}
	oracle := filepath.Join(dir, "oracleA")
	cmd := exec.Command("go", "build", "-o", oracle, "867A.go")
	if out, err := cmd.CombinedOutput(); err != nil {
		return "", fmt.Errorf("build oracle failed: %v\n%s", err, out)
	}
	return oracle, nil
}

func runProg(bin, input string) (string, error) {
	var cmd *exec.Cmd
	if strings.HasSuffix(bin, ".go") {
		cmd = exec.Command("go", "run", bin)
	} else {
		cmd = exec.Command(bin)
	}
	cmd.Stdin = strings.NewReader(input)
	var out bytes.Buffer
	var stderr bytes.Buffer
	cmd.Stdout = &out
	cmd.Stderr = &stderr
	if err := cmd.Run(); err != nil {
		return "", fmt.Errorf("runtime error: %v\n%s", err, stderr.String())
	}
	return strings.TrimSpace(out.String()), nil
}

func main() {
	if len(os.Args) != 2 {
		fmt.Println("Usage: go run verifierA.go /path/to/binary")
		os.Exit(1)
	}
	bin := os.Args[1]
	oracle, err := buildOracle()
	if err != nil {
		fmt.Fprintf(os.Stderr, "%v\n", err)
		os.Exit(1)
	}
	defer os.Remove(oracle)

	const testcasesRaw = `100
2
SF
2
FS
2
SS
2
FF
100
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
19
SFSFFFFSSFSFFSFFSSF
5
SSSFS
56
SSFFSFSSFFSFSSFSFFSFFFFSFSFFSFFSFSSFFFSFSFFSSSSSSFFFFFSF
96
SSFSFFSFFFFFSFFSSSSSFSSSSFSFSFSSFFSSSFSFFFFFFSSFFFFSFSFSFSSSFSSSFFSFSSFFFSFSSSFSSFFSFFSSSSFSSFSF
14
SFSFSFFFSFFFSS
27
FSFFSFSFFFSSSSSSSSFFFFFFSFS
79
FSSFSFSFSSFSFSSSFFFSFFSSFSSSFSSSSFSSFSSSSFFFFFFSSFSSSFFFFFFSSFFSFSFFFSSFSSFSFSF
13
FSFFSFSFFSFSS
33
SSSFSFSSSSFFFFSSFSSSSSFFSFSSSSFSS
40
FSSSFSFFFFFSFFSFFSFSSFSSSFFFFSSSFSSFFSSF
65
FSFFFSSSFSSFFFFSFSSFSSFFSSFFFFSSSFSFSSSFSFFFSFFSFSSFFSFFSFSSFSSSF
28
SFSSFFFFSFFFSSFSFSSSSFSSFFFF
99
FSSFFFFFFFSFFSSFSFFFSFSFSFFFFSFSFSFSFFSSSFFFFSFFFSFSFSFSFSFSSSSFFFSSSFFSSFFSSFFFSFFSFFFSFSSFFFSFSSS
76
FSFFSSSFFFFSSSFSSSFFFSSSSSSSFFFFSSSSFSFFFSSSFFFSFFFFSSSSSSFFFFSFSSSSFSSFFSSF
85
FSSSSSFSFSSSFSFSFFFFFSSSSFFSFFSFSFSFSSSSSFSSSFFSFSSSFSFFSFSFFSFSFSFFSFFSFSFSSFFFFSSFS
39
SSFFFSFFSSSFFFFFFFFSSSFFFSFFFFFFSSSSFFS
91
FFFFFFFSSSFSSSSFSSFSSFSSSSSFSFFFSSFSFFFSFSFFSSFFSFFSFFSSFSSFFFFFFFFSFSSFSFSFFFFSSSSFFFFFFFF
60
SFFSFSSSFFSFFFFFFFFFSFFFSSSSSSSSFSFSFSSSFSSFFSSFSFFSFSSSFSFF
89
FFSFSSFSSFFFFSFFSSFFSFFSSFFSFSSFSFSSFFFFFFFSFFFSFSSFSSFSSFFFFSSSFSSSSSSSFFFSSFSSSFFFFSSFF
19
SFSSFSSSFFSFSFSSSFF
94
SSFFSFSFSFFSFFFFSFSSSSSSFFSFFFFSFSFSFSFFSSSSSFFFFSSFFFSSFFSSSFSFSFFFFFFFSSFSSSSSFFFFSSSFSSSFFF
34
SFFFFFFFSSSFSSFFSSFSFSFSSSFFSFFFFS
57
FFSFFSSSFFSSSSFFFSSSFSFFSFSSFSSFSSSSFSSFSSSSSFFSSFSSFSSSS
41
FFFSSFFFSFFSFFFSFFSSFFSFFFFFFFSSSFSSSSFSS
72
FFSSSSSSFFFSSSSFSFSFFSSFSFFFSFSFSFSFFFSSFSSSSFSSFSSFSFSSSFFSFSSSFFFFFFSS
25
SFSFSFFSSSSFFSSSFFSSFSFSF
7
SSFFSSF
13
FFFFFFSFSFFFS
78
FSFFFSSSSSFFFSFSFSFFSSFFSSSSFFFFFFFSSSFFFSSSFFSSFFSSSFFSFSSFFFSSFFSSFFSSFSSSSS
77
SFFSSFFFFSSSFSSFSSSSSSSSFFSFFFFSSSSFFFFSFSSFFFSFSFFFFSFFFFFFSSFFFSFSFFSFFSSFS
34
SFFSFFFSSSFSSSFFFSSSFFFFFFSSFSSSSS
93
FFSSFFSFFFSSSFFFFFSFFFSFSFSSFFFSSSSSFSSSSSFSSSSSFFSSSFSFFFSSSFSSFSFFFSSSSSSSSFSSFSSFSSSFFSSFS
31
SSSSSSSSFFFSSFSFFFFFFSFSFFSSSSF
37
FFFFFFFFFFSFSFSFSSSFSSSSFSFFSFFFSFSFF
15
SFSSFSSSFFFFFSS
50
SFSSSFFFSFSSFSSSSSFFSSSSFFFFSFSFSFSSSSSSSFFSSFSSSS
58
SFSSSFFSSFFFSFSFFFSFFFSFSFSSFSFFFFFFSFSFSSFFSFFFFFSFSFSFFS
52
FSFSSSSSSFFFSFFSFFSFSFFFSFSFFSSSFSFFSFFSSSFSSFFSFFSS
44
SSFSFFFFSFSFSSFSFFSFFFFSSSSSFSFFSFFSSFFFFFSF
25
SSSSFFFFSFSFFFFFSSFFFSFSF
19
SSSFSSSFSFSFFFFSFFF
40
FFFFSSFSFSFSSFFFFFFFFFSSSSSSFSFFSFFFFSFS
42
FFSSFFSSSFFSFSFSFSFSSSFSFFFFSSSSSSSFSFSFFS
4
FSSS
90
FFSSSFSSFSFFSFFSFSSSSFSFSSSSFFSFFFSFFFFFFFSSSSSSSSFFFSSSSSFFFSSFFFSFSFSFSSSFSSFSSFSFSFSFSF
71
SSFFSFFFFSSSFSSFSSSSSFSSFFSFFFSSFFFSFFFFSFSFFFSFFFFFSFSSSFSFFFFSSSFSFFF
71
FSSSFSFFSFSFSSFFSFFSSSSSSSFSSSSSSFFFSFSSFSSFFFFFSSSSFFFFSSSSSFSFFSSFSFS
63
SFFFFSSFSFFSSSFSFFSFSSSFSSFFFFFSFSFSSFFFSSFFFFSFSFSSFFFSFSSFFSF
76
SFFSSFSFSSSFSFSFSSSSFFFSFFFSFSFSSSFFFFSFFSSSSSFFSSSSFFSSSFSFSFSFFFSSSSSFFSSF
57
SSSSFSFFFFFFSSSFSSSFFFSSSSSSSSFSSFSSSSSSSFSFSFSFFFFFFFSSF
74
FSSSSFSSFFSFFSSSFFFSSSFFFSFSSSSSFSSFFSSSSFFSSFSFSSSFFFFFSFFFFFSFSSFSSFFSFS
82
SFFSFSFFSSFFFSFFSFSFFSSFSSFSSFFFFFSFSSSSFSFFSFFSFFSSFSSFSFSSSSFSSFSFSSFSFFSSFFFFFF
45
SSFFSFSSFFFFFFFFFSFSFSSFFSFFFSSFSSSSFSSSSFFSS
36
SFSFFSFFFFFSSFFFFFFSSSFFFSFSSSSFSFSS
40
SSFFFFSSSFSSSFFFFFFFSSSFSSSSSSFSFFFFFSFF
32
SFSSFSFFSFFSFFSFSFFSSSFFSFSSFFSF
94
FFSFFSFSFFSSFFFFSFSFFFSFSSSFSFSSSSSSSSSSFFSFSSFSSFSFFSFSSSFSFSSSFFFFFSSFSSFFSFSFSFFSFSSSSFFSFF
56
FSFSFFSSSSFFFSFSFFSFSSSFFSSFSSSFFFFFSSSFFSFSSSFSSFFFSSSF
45
FFFFFFFSFSFFFSSSSSFFFFSSFSSFFFSFSFSFSFFSFFFSF
44
FSFSFFFFFSFFFSFFFFSFSSSFSFSFSFSSFSFFSSSFSFSS
97
FSFFSSSFFSFFFSSFFFSSFFSSFSFFSFSFSFSSFFFFSFSFSFSSSFSFSFFSFSSSSFSSFSSFSSFFSSSSFFFSFFSFFSFFFSSSSSFSF
30
SSSFFFSFFSSSFFFFFFSFFFFSFSFSSF
11
FSFFSFFSFFF
56
FFSFFFSSSFFFFSFSFSSSFFSSSSFFFSFFSSSSSSFSSFFSSFSSSSFFSSSS
79
FSFFSSFSSSSSSSFSFSFFSFFSSSFFFSFFFSSSFFSFFFSFSFFSSSFSSSFSFFSFSSFFSFSFFFSSSSFSSFF
49
FSFFSSSSFSSFSFSSFFSSSFFFSSFSFSSSSFFFSSFSSSFSSFSFS
71
SSFFFSFFSFFSFSFFSSFFFSFSFFSSSSSFFSFFSSSSFFFFSFSFFSSFFSSSFSFSSSSFSFSSSSS
6
FFFSSS
10
FFFFSFFFFF
39
FSFSFSSFSSSFSSSFFSFSSSSFFSSSSFFSFFSSSFS
89
FSFFSSSFFFFFFSSFFFFSFFSSFFSSFSSFSSFSSFSFFSSFFFFSFSSFFSFSSSSSFSSFFSSSSSSSSSFSFFSSFFFSSFSFF
40
FFFFFSSSFSSSSSFSSFSFFFFSFFSSSFFSFFSFFFSS
65
SFFFFFSSSFFSFSSFFFSSSSSFFFFSSFFFFFSFSFFFFFFFSSFFFSFSSSFSFSFFSSSSS
61
FSFFFSFSSFFFFSSSSFFSSFFFSFFSFFSFFSFFSSSSFFFFSFSFSSFFSFSSSFSFS
47
SFFFSSSFFFFSFFFSSFSFSSFFSFSSFSSFSSFSFFFFFFSSSSF
24
SSSSFSSFFFFFFFFSSFSFSFSS
51
FSFSSFFFSSFSSSSSSSFSSFFFFSSFSFSFFFSSSSFSSSSFSFFFSFS
7
FSSFSSF
15
SFFFSSSFSSSSSFS
2
SF
85
SFSSFSFFSFSFSFSSFFSSFFSFFFFSSFSSSFSFFSSSSFSSSFFFFFFFFSSFSSFSFSSSSFSFFFSSSFFSSSFSFFFSS
78
FSSSSSFSFFFSSFFFFFFSSFFFSFFSFFFFSSSFFSFSSSFFFSSFSFSFFSSFSSFSFFSFSFFFSFFSFSFFFS
19
SSFSSFFSSFSFFSFFFFF
73
SSSSSFFSSSFSSFFFFFFFFFFFFFSSFFFFFSFFFFSFSFSSFSFSFFFFSSFFSFFFFSFFFSFSSFSSF
20
FFSFSSSFFFFFSFSSSFFF
33
FFFFFFSFSFSSFSFFSFFFFFSFSSFFFSFSS
42
SSFSFFSSSFFFFFFFFSSFSFSFFFSSSFFFFFFSFFSSFS
97
SFSFSSSSSSFSFFFSFFFFFFSFFFSFFSFSSSSSFFSSFFSFFSFSSSSFFFSFSSSSSSSSFFFFFSFSFFSFSSFFSFFFSSFFFFFFFFSSF
43
SSSFSSFSSSFSSFFFSSSFFFFSSFFSSSSFSFSFFSFFSFF
31
SSFSFFSFFFSSSFSSSSFFSSSSSSSFSSF
43
SFFFSSSSFFSFSFSFFFSSSFSSFSSSSFSSFFFFSSSFSFS
48
SFFFFSSSSSSFFSSFSFFSSFSFSSSFSFSSFFFFSSFFFFSFSFFS
78
SFFFSSSFFFSSFSFFSFFSFSFSFFSSFSFSSFSFSFFFSSSSFFFFFSFSFFSSFSFSFFSFSSSFFFFFSFSSFS
33
SSFSSSFSFFFFSFFSSFSFFSFFFFSFFSFSF
56
SFFFFSSSSSFFSSFFFSSFFFFFFFSSSFFSFSSFSFFFFFSFSSFSFSSSFSFS`

	reader := strings.NewReader(testcasesRaw)

	var t int
	if _, err := fmt.Fscan(reader, &t); err != nil {
		fmt.Fprintf(os.Stderr, "failed to read test count: %v\n", err)
		os.Exit(1)
	}

	for i := 1; i <= t; i++ {
		var n int
		var s string
		if _, err := fmt.Fscan(reader, &n); err != nil {
			fmt.Fprintf(os.Stderr, "test %d: read n: %v\n", i, err)
			os.Exit(1)
		}
		if _, err := fmt.Fscan(reader, &s); err != nil {
			fmt.Fprintf(os.Stderr, "test %d: read s: %v\n", i, err)
			os.Exit(1)
		}
		input := fmt.Sprintf("%d\n%s\n", n, s)
		want, err := runProg(oracle, input)
		if err != nil {
			fmt.Fprintf(os.Stderr, "oracle error on test %d: %v\n", i, err)
			os.Exit(1)
		}
		got, err := runProg(bin, input)
		if err != nil {
			fmt.Fprintf(os.Stderr, "test %d failed: %v\ninput:\n%s", i, err, input)
			os.Exit(1)
		}
		if strings.TrimSpace(got) != strings.TrimSpace(want) {
			fmt.Fprintf(os.Stderr, "test %d failed:\nexpected: %s\ngot: %s\ninput:\n%s", i, want, got, input)
			os.Exit(1)
		}
	}
	fmt.Printf("All %d tests passed\n", t)
}
