package main

import (
	"fmt"
	"os"
	"os/exec"
	"strconv"
	"strings"
)

func solve(n int, s string) string {
	b := []byte(s)
	ops := 0
	for {
		hasB := false
		for i := 0; i < n; i++ {
			if b[i] == 'B' {
				hasB = true
				break
			}
		}
		if !hasB {
			break
		}
		k := 0
		for k < n && b[k] == 'R' {
			k++
		}
		nb := make([]byte, n)
		for i := 0; i < k; i++ {
			nb[i] = 'B'
		}
		nb[k] = 'R'
		for i := k + 1; i < n; i++ {
			nb[i] = b[i]
		}
		b = nb
		ops++
	}
	return strconv.Itoa(ops)
}

var testcases = []struct {
	n int
	s string
}{
	{25, "BRBBBBBBRRBRRBRBRRBBRBBBR"},
	{36, "BBBRRRBRBBRBRRRRRBRRBBRBBRBRBBRBBRBR"},
	{13, "RRBBRRRRRRBBR"},
	{14, "BBBBBRBRBBRRRB"},
	{8, "RBRBBRRR"},
	{45, "RRRRRRRBRBRRRRRRBRRRBRBRRRBBBRRBRRBRBBBRRRRRB"},
	{34, "BRBRRBBBBBBRRBRBRBRRBBBBRBBBRRRBRR"},
	{15, "BBBRBBRRBRBRBBR"},
	{3, "BBB"},
	{30, "RBRRRRBBBRRRRRRRRBBRRBBRRBBRBR"},
	{42, "BRRBRRRRBBBRBBBBRRBBRRRBBBBRBRRBRRBBBRBRBR"},
	{4, "BRRB"},
	{26, "BBBRRBBBBRBRBBRBBRRBRRRRRR"},
	{25, "RRBBBBRBRBRBRBRBRRRBRRBBB"},
	{14, "RRRRRBBBRRBRBB"},
	{34, "BBBBRRRBBBRRBRBBBRRRRRRRBRBBRRBBBR"},
	{37, "RRBRBBBBRRRRBBBRBBBBBBRRRRBBRRBBRBRRB"},
	{27, "RBBBRRBRRRRBRBRBBRRBBRBRBBR"},
	{34, "RRBBBRBBRRRBBRRRRBBRRBBRRBRRBRRBBB"},
	{2, "BB"},
	{47, "BRBRRBRBBRRRBRRRRRRRBBRRRRBRBBBRRRBBBBBBRRRBRBR"},
	{9, "RBRRRBBBR"},
	{9, "RBRRRBBBR"},
	{38, "BBBRRBBRBBRBBBRBBBRRRBRRBBRBBRRBBRBBRB"},
	{49, "RBRBBRRBRBRBBRBRBBRRBRRBBBBRBBBRRRRBBBRRRRBBBRRRB"},
	{41, "BBBBBRRRRBBBRBBBBRBBBBRBBRBRRRBBBRRRBRBRR"},
	{40, "RBBRRBRRBBBBRBBBRBRBRRRBBBBBBRRBRRBRRRRB"},
	{4, "RRBR"},
	{46, "BBBBRBBBBBRBBRRRRBRBRRRBRBRBRBRRBBBBBRRRBRRBRR"},
	{17, "BBBBBBRRBRRBBBRBB"},
	{30, "BRRRRRRBRBRBBRRRBRRBBBBRBRBBBB"},
	{18, "RRRRRBRRBRBRRBBRBR"},
	{44, "BRRRBBRBBBRRRBBRRBRRRRRBRRRRBBRBRRBBBBRRRBBB"},
	{46, "RBRBRBBBRRRBRBBRBBRBRBRRBRBRRRRRRBRRBBRRBBRBBR"},
	{42, "BBBRBBBRRBBRRRRRBRRRRRRRBRBRRBBBRRBRBBRBRB"},
	{11, "BBBBBRBBBRB"},
	{44, "RBBRBBBRRBRBBRBBBRRBRBRRBRRRBBBBBBBBRRRRBRBR"},
	{47, "BBRRBBRRRRRBBBBBRBBBBBRBRRRBBBRBRRBRRBBRRRBRBRB"},
	{16, "BRRRBRBBBBBBBRBR"},
	{32, "RBRBBBBRBBRBBRBBRRRBBRRRRBRBRBBR"},
	{49, "BBRRBBRRRRBRRBRBRRRBRBBBBBRBRRRRBRRBRBRBRBRRBRRRB"},
	{39, "BBBBBRRBRRRRBRRBRBBRRBRBRBBBBBBRRBBRBRB"},
	{7, "RRBRRBR"},
	{21, "BBBRRBBRRRBBRBRRBRRBB"},
	{11, "RRRRRBRBBRR"},
	{16, "BBRRBRRBBBRBRRRB"},
	{46, "RRRRBRRRRRRBRBBBRRBRBRRBBRBBRBBRBRBBRBBBRBRBRB"},
	{26, "RRRBRBBBRBBRRBBBRBRBBRBBRR"},
	{17, "RBBBRBBRBBBRBRRRB"},
	{11, "RBBBRRBRRRR"},
	{11, "RRRBBBBRBBR"},
	{22, "BRBBRBBBBBBBRRRRRRRBRB"},
	{6, "RRRBBB"},
	{7, "BBBBRRR"},
	{50, "RRRBRBBBRRBRBRBRBBRBRBRBBBBBRRBRBRBRRBBBRBBRRBRBRR"},
	{43, "RRRRRBBRBBBRRRRBBBRRBBBRRBBRBBRRBRBBBBRRBBB"},
	{15, "BBBBBBBRBBRBRBR"},
	{48, "RBBRRBBBBRBBBRBRRBBBRBRRBRBRBRRRBRRRRBRRRRRBRRBR"},
	{35, "RRRBBBRBRBRBRBBBBRRBRRBRRRBRBRBRRBR"},
	{33, "BBRBBRBBBRBRBRBBBRBRBBRBRBBBRRBBB"},
	{42, "BRRRBRRRBRBRBBRBBRRBRBRBRBRBRBRRBBRRRRRRBR"},
	{43, "RBBBBRRBBBBBBBRRRRRBBRBRRBRRBBRRRBBBRRBRRBB"},
	{20, "RRRRBRBBRBBRBBBRBRRR"},
	{21, "BRBBBBRRBRRRRBRRBBBRB"},
	{19, "BRRBRRBRBBRBRBRBRRR"},
	{32, "RRBRRRRBRBBRBBRRBBRBRRBBBRRRBRRB"},
	{13, "BBRBBRRBBRBRB"},
	{44, "BRRRBRBBBRRRBRBBBRBBBBRBBRRRBBRRRBRRRBRBBRRB"},
	{19, "BBBBRRBRRRRBRRBRRRB"},
	{46, "RRRRRBRBRRBRBBRBBRRRRRRRBBBBBBBRRRRRRRBRBRBRRB"},
	{43, "BBBBRRBRBBBBBRBBBBBBBBRRBRBRRBBBBBBRRBBRRRR"},
	{17, "RRRRBBRRRRBRBBBBR"},
	{38, "BRRRRBBRBRBRRBRBRRRBRRRBBBRRBRBBBBBBRB"},
	{49, "RRBBBBRBRRRRBBRBBBRBRRRRRRBBBRBRRBRRRBRRBRBBBRBRR"},
	{42, "RRRBBBBRBRRRRBRRRRBRBRBRRBRBBBBBRRBBBBBBRR"},
	{10, "BBRRRRRBRR"},
	{34, "BBBBBBBBRRBBBRRRBRBBRRRRBRBRBBBBBR"},
	{42, "RBBRRBRBBBRRBRBBBBRBBRBBBRRBRBBRBRBRRBRRBB"},
	{14, "RBRRBRBBBRBBBR"},
	{3, "RRR"},
	{36, "BRBBBBBBRRRBRBBBBBBRRRRRBRRRRRBRBRRB"},
	{19, "RRRRRRBBBRBRRRBRRRB"},
	{35, "BRBRBRRRRRBRRBRBRRBBBRBRRBBBBBRBBRR"},
	{25, "RRRBRBBRRRBBBBRBBBRRRBBBR"},
	{30, "RBRRBRBRRRRRRBBRRRRBRRRRRBBBBR"},
	{23, "BRRRBRRRRRBBRBBBBBRRBBR"},
	{15, "RBRRBBRBRRBBRBR"},
	{13, "BBBBRRBRBRRBB"},
	{10, "RBBRRRRBBR"},
	{3, "BBR"},
	{44, "BRRBRRRRBBBBRRRRBRRRRRRRRRBRBBBBRRRBRBBBBBRB"},
	{42, "RRRRRRBBRBBRBBRBRBBRBBRBRBRBBRBBBRRRBRBBRB"},
	{31, "BBRBBRRRBBRRBBBRBBRRRBBBRBBBBBR"},
	{6, "BRRRBB"},
	{16, "BRBRBRBBRBRRRRBB"},
	{29, "RRBBBRBBRRRRBRBRBRRBRRRRBRRBB"},
	{45, "RBRBRRRBRBRBBRBBRBRBRBBBBBBBBRRRBBRBBBRRRBRRB"},
	{45, "BRRBBBBBRRRRBRRBBRRBRBBRRBBBBRRRBBBBRBBBRBBBR"},
	{26, "BBBBBBBRBRBBBBRRBRBRBRRBRR"},
	{12, "RRRRBBRBBBBR"},
}

func main() {
	if len(os.Args) != 2 {
		fmt.Println("usage: go run verifierB.go /path/to/binary")
		os.Exit(1)
	}
	bin := os.Args[1]

	for idx, tc := range testcases {
		expected := solve(tc.n, tc.s)
		input := fmt.Sprintf("%d\n%s\n", tc.n, tc.s)

		cmd := exec.Command(bin)
		cmd.Stdin = strings.NewReader(input)
		out, err := cmd.CombinedOutput()
		if err != nil {
			fmt.Fprintf(os.Stderr, "test %d: runtime error: %v\n%s", idx+1, err, string(out))
			os.Exit(1)
		}

		got := strings.TrimSpace(string(out))
		if got != expected {
			fmt.Fprintf(os.Stderr, "test %d failed\nexpected: %s\n got: %s\n", idx+1, expected, got)
			os.Exit(1)
		}
	}

	fmt.Printf("All %d tests passed\n", len(testcases))
}
