package main

import (
	"bufio"
	"bytes"
	"fmt"
	"os"
	"os/exec"
	"strconv"
	"strings"
)

const testcasesRaw = `100
39 13 AEIHGMEHFJDICECMBJMEILMJCEBLBKFHIBFGFJK
42 7 DDGECAGEAAFGDFGGFFAEDGGCBFCFGABEBBGBGEDAAC
48 17 DJJDKGJOCMKHJFGFBIPCCEEBCMQIQHGNIOPLCKDPKGHAIDHL
31 26 KNBDZEWHBSURTVCADUGTSDMCLDBTAGF
26 23 PGBVARNTDICHCUJLNFBQOBTDWM
23 7 CFDGEBFFBGAGFBGBCECAEDF
6 6 DFDEEC
32 21 MIERAOCKBRIEHPLTJLSUTEJMNUCATGKF
22 8 HGGAGGACHBECHHAAHFEHAG
42 7 FAGFBADFDCABAFGAGFEEABAEFBGCCFBADGDFAACDGG
20 4 BCABCAAABCCCADDDCBBD
37 19 AEEIKKLCKBBIFESJLMREJDPHBJFQCJMKJNDDR
46 16 KKDPDPNBJKEFMCCCGHBMADMJOPGNCLHIFNGLDCAOGDPMIG
22 21 GTEDGOMLREDTPESMUNQPKP
28 16 HAKKKBEIEMJPCCBCHEBJAOKFEOLM
49 17 BCQCNGJNPMHAAFJQIKCPIJNMMBFEHJKBBPNEPCELNBOMOBDPE
3 1 AAA
40 23 ULGMPDBTWOTUKUDVWTJEMJVDQGBMOLGOLUCBBPIA
30 17 HCQQNQJDENNCDNCDNEAONNAPKICLCD
13 12 FFCADFBJCDADK
45 22 DAJLATHEFODPLIEAGLKPJJRUKFSCDRSJFMEEHKQHHFJLN
23 22 ETAMCCENJRNESNJULCHOULU
20 17 MNANKOGLJPCFDIDEOMFN
25 14 DHFICFHKKBHMDEANLHJHADEBM
30 21 RTENPCPHRMIUADIBAIMQSMODILJGTC
6 2 BBBAAA
29 3 BBCACCCACABCCBCBBBBCCAAACABBC
23 15 IKEFKHLGDHHLIFHKAHECLHA
26 20 ALPMAQCCMALBDTAIJHESJGDNOK
23 13 FGKKGCHLCIFCDCHFMGGMHGL
20 8 HDAGADBCFACDEBEFGHAG
48 19 PIPGKIBBBFLAJAECNHMRHOGKDCKKROKIAQBGLCGQLGGIJJQM
39 9 FDAEIBAHHHAGHHHBBBDBCGDHBGIGACDHDCEFFGB
36 18 RGJOQORIIHADDFNHGJARQNBDMIDLHRJHHCQJ
32 22 HLUPJSFEARQKLSUAEMEFQCEGPSGHEHML
38 20 EPDTAQTLPOJAHRFPPRKCIETMGKJMBGBKHKOHIL
27 22 JALSRBUELAPUBAHBAHUKCBLVNEG
42 15 CFECKFLMLGGAGOEIIMLKLHMAJOBGGCAICJNKINLLCB
26 11 CDACKICBGJBJKHCJJAEFGAKAHB
30 12 KCHDIFCLGFEHGAEIEIHAIJIEKAHGLB
35 13 HAAELAEKKJLMEKMDMIIFGEDBJFMDJKLIKFC
26 5 AEAEBCCCCCDDEDBABEADBCADCE
11 7 EDCGBEBAFFB
26 19 QRMNIJJANIIRQRKKGNEAQESMLO
37 2 BAABAABBAAABABABABAAABABBBBBBBABABABA
37 25 MNYUUVMWBSOLSESWIKAMPQEBCSLLACGWDVRPB
12 11 FGCKEGKCJCGE
20 17 FEEPBQBMFLCCFIGIKIIQ
24 15 MOHICAKJCKIAOMFNBDKMHJDM
48 15 CLFOKCHMIAIBNIFANMBBGJFJHFNGIFNNKBCFOACLCAFOJDAG
22 21 JMBTFLCNBOLTTIJSONFAOI
31 7 ACAAACABDEFFACDGEFGFDDAGAEGDGGG
10 9 IBBFFBHACI
46 21 JBAMKFREFFFUHTKAPUMBHHUJKFHLHFNOLSEMSAFSAMFEAA
43 11 AAABJJCCKGAGGJKFDCFIDIGBCGJKFBGGDHGDGDKHGJB
26 9 IFIAHDEAFGBIACGAGGGBHHCCFH
24 14 JNEMIBFFCKFMHKIMADECLJFE
15 13 EIGAKGEGLDFCCBJ
22 12 AGJGHBKLLKBGILICCCDCDA
25 17 PLJKDNIFKQKEMJHMLMPQJNNDE
5 5 EEEAB
40 20 TQDITFMCBADLPKDOLSIPHFRRCQFAFQNTGOMIASEM
34 6 EADAFEDCBEDADEACEDEFDDCBBECBCEBDAA
41 16 NCIPHDJELDEBEGABMPDPLKDAHHPJIHAPLKCCJNHLM
29 25 HJGXYPVLJMTEYDMLQPHUWLULNILMY
47 25 JDPJDOELHXFKPHDVMMOQOSTHVMQJPHKQVACPKMHNBSYBNCI
27 7 BABGFCABAADEABAGEEBAFDBGAEE
18 14 ICDDGGHMAGDGMAJEAJ
35 12 FKHKCJIBEBLBEALCJKCGDJKFDGIIBIBLHBI
45 15 CHIFCGEGBJIFNNNDHDFHMOGAHLOAIGMMHDGDEHHCDHEFK
25 16 CGJDBEKBKFOMGNPGFMBKGKFNE
43 21 TPSGTOBHPTKRGABBEHOTHDQNUUJKPGFLRLOMOKOCEHD
29 25 MOWRGLWBAMGCNSSNRGUAVEQUPJMRR
8 3 CCBAABCB
15 10 ADJAJIFCHEBJHED
37 13 LIFDJEBACFKJJHBIHGFGLABGJKCMCABLGDAKE
33 9 BFEFDIIAFIIACHAEFCFBIGBEBIBCHAIDF
39 4 BBBDBDCBCCBBDCBCAACCCAAACABCBCDADDAADCB
25 10 GEAAAEBFFIEADICEJAGGEJDEF
43 26 POWDNLFQBHWZPMAHCJDFEOAYLQNDQHPJIMNPWBFWQLG
17 8 DECCEACDGCDCCDEAH
32 26 BNFMQMGMRQPDECRACAXHXMOVINLVMIXC
30 25 SHXGBYBQCWOHOWYYVETUQJATELVLLJ
33 17 EAPGMKPJOEPJKLMMMQJHGNGIQFQEQQPKI
33 14 HKIAMLDEHLBADJBNEMANNDCJCKFJMEAKK
2 1 AA
33 8 HFFBGBACAEFDGDFCCHCGDAAGACBGEFDAF
25 5 CDDECCADBAECEDEDDBEDBAEAB
39 24 JVXDVNIIDULQRCABTAEDNMPAKUECWMUSXHBGNAB
45 20 MERJNMRBOREREGSFCSPJIIGMABQCAJEEQEDKAKEKSCCLG
37 9 FHHIIBBFHGGIHIGIBDCGIFCBCCAGBBIEEFHGF
45 24 TOQLHQBXMLKQAHSCPDLNTHRAQQDBSLBLFKIPPNAUHUUPX
35 24 VXFBXPQVFMWJVSPGAWOTTVFTOKSKNSUEQNM
31 8 GEDDEDFHDFCFDCECBHHDCFDBHDEGEDF
34 14 LAADDJNCNIHBEIELHGNFNKLLNLGANBAFCM
48 9 IHEIGHFDBBBIAIFBDAABEBGCIDEECCDCCDEHECEDBCGCDAFI
37 22 VEICTITHAEGSVANEEPRBQKHVFOKVOHUUIVGDL
33 16 LJGJMCFMDDEOENIGFCIOKMBLMMEEBJONG
28 15 GBBIGBIKHLKCADDDBJGGBONIDIDD
21 16 GDEGNMIPALLGBGOGGAEHO`

// Embedded reference logic from 1038A.go.
func referenceAnswer(n, k int, s string) string {
	reader := bufio.NewReader(strings.NewReader(fmt.Sprintf("%d %d\n%s\n", n, k, s)))
	var rn, rk int
	var rs string
	if _, err := fmt.Fscan(reader, &rn, &rk); err != nil {
		return ""
	}
	if _, err := fmt.Fscan(reader, &rs); err != nil {
		return ""
	}

	counts := make([]int, 26)
	for i := 0; i < len(rs); i++ {
		c := rs[i]
		if c >= 'A' && c <= 'Z' {
			counts[c-'A']++
		}
	}
	minx := rn
	for i := 0; i < rk; i++ {
		if counts[i] < minx {
			minx = counts[i]
		}
	}
	result := int64(minx) * int64(rk)
	return fmt.Sprintf("%d", result)
}

func runCase(exe string, input string, exp string) error {
	cmd := exec.Command(exe)
	cmd.Stdin = strings.NewReader(input)
	var out bytes.Buffer
	cmd.Stdout = &out
	cmd.Stderr = &out
	if err := cmd.Run(); err != nil {
		return fmt.Errorf("runtime error: %v\n%s", err, out.String())
	}
	got := strings.TrimSpace(out.String())
	if got != strings.TrimSpace(exp) {
		return fmt.Errorf("expected %q got %q", exp, got)
	}
	return nil
}

func main() {
	if len(os.Args) != 2 {
		fmt.Println("Usage: go run verifierA.go /path/to/binary")
		os.Exit(1)
	}
	exe := os.Args[1]
	scan := bufio.NewScanner(strings.NewReader(testcasesRaw))
	scan.Split(bufio.ScanWords)
	if !scan.Scan() {
		fmt.Println("invalid test file")
		os.Exit(1)
	}
	t, _ := strconv.Atoi(scan.Text())
	for i := 0; i < t; i++ {
		scan.Scan()
		n, _ := strconv.Atoi(scan.Text())
		scan.Scan()
		k, _ := strconv.Atoi(scan.Text())
		scan.Scan()
		s := scan.Text()
		input := fmt.Sprintf("%d %d\n%s\n", n, k, s)
		exp := referenceAnswer(n, k, s)
		if err := runCase(exe, input, exp); err != nil {
			fmt.Printf("case %d failed: %v\n", i+1, err)
			os.Exit(1)
		}
	}
	fmt.Println("All tests passed")
}
