package main

import (
	"bufio"
	"bytes"
	"fmt"
	"os"
	"os/exec"
	"strconv"
	"strings"
)

func expected(x, y string) string {
	if len(x) != len(y) {
		return "-1"
	}
	for i := 0; i < len(x); i++ {
		if y[i] > x[i] {
			return "-1"
		}
	}
	return y
}

func runCase(exe string, input, exp string) error {
	cmd := exec.Command(exe)
	cmd.Stdin = strings.NewReader(input)
	var out bytes.Buffer
	cmd.Stdout = &out
	cmd.Stderr = &out
	if err := cmd.Run(); err != nil {
		return fmt.Errorf("runtime error: %v\n%s", err, out.String())
	}
	got := strings.TrimSpace(out.String())
	if got != strings.TrimSpace(exp) {
		return fmt.Errorf("expected %q got %q", exp, got)
	}
	return nil
}

func main() {
	if len(os.Args) != 2 {
		fmt.Println("Usage: go run verifierB.go /path/to/binary")
		os.Exit(1)
	}
	exe := os.Args[1]
	const testcasesRaw = `100
szycidpyopumzgdpam
azhgjawzxozdzqryel
dxkxwqnqvgjjspqmsbphxzmnvflrwyvxlcovqd
uzajzxqrxcvexqqvualozlaxyawfzzvaearcij
iuwjowkppdajmknzgidixqgtnahamebxfowqvnrhuzwqohquamvszkvunbxjegbjccjjxfnsiearbsgsofywt
vdvqkqfwqctueyivyabikvchxxmzadgzevrcyxtebzvnoonoibmxzeyuabzfavazladeoerjcekdutawiiale
qyzkcqvffyeek
qzgawzxdhzatt
roroamkfipazunsabwlseseeiimsmftch
fxzzikdqrtdzxmuxbwvdvudekgsfnizcm
tvvwcohmznmfkoetpgdntrndvjihmxragqosaauthigfjergijsyivozzfrlpndygsmgjzdzadsxarjvyxuecqlszjnqvlyqkado
wmvxpieyzwhwewvqmtaljyqqxkevvozrenbtxxuydfawygrevpizrxpzzdvpfxbzbeugbznhqjayqzefmofmrxlpzmmpmqzelfvg
ecoujabrbqebiydncgapuexivgvomkuii
mcynlsayesaakcufbewmyeilmcegxgztz
spdeuoqrxswqrajxfglmqkdnlescbjzurknjklikxxqqaqdekxk
xicrvpqizlowujoyzawbctgroslsldzwlozeayhjzojrkwvwgzu
ojeqoseryfiuanxvsblnmjvyvaccamioizzluxpy
hzdfuxsqnthpnpgxtbnlajwzueycjpazvoqgpmti
xrjpuzrgzytkpdayxvlwibruojydhqiiwhneeignrutbrtqeniipwj
gpcszzsxzzpbelszygwyavhuuidbcrbmhabdbfepexssnxhwjogais
emwdxlcurlrrzxqvsatjoveecsevgpzykljfezmomdteijvvzutarauemxrdo
dtldpwdvxyxvzywwyybxeybvbxdwhgfhfryrbmwepdakgtxwzmziysykdruav
zbqxgwqwturchmyodsubmcrdupbqhya
jbezvyxxieiwfcieeewayvobcbbemzn
jgvxmlxfhjwelprjcq
qhtzrmzblgxvntyova
dzgysmvprthibufvvrqhniyvnmipdvefraoybpgmxrkhdcvxbnogftqgqmqlghlvsyyckbobtfejpbsqcsmcmzqsujmi
tzgnkwylqyjjblhwurqzcusdnsrqyirytgtebddigtqydekfdzxbesvgojuwdemcuqobqacbyddbzpxcjzjuuzyuzgra
ybzoolhqogwpkwuemnbudlzaiyrxbjmakkjszbgwckdvuceywjntkhauwwfyyyqxsuljjmnqozcgnh
zjzjerefpuzdpzahoxzxbjzfazbweasudeiumjvkatjfdbjobvbhmaehznhzlvxzhyongvfwfmtbez
xefouueefctihlukfipjcnerlodevkcvfprbbxgulxlqlzquzvlkudfmbitwzgbhjksmhlybhjwsagdehlqiefhcjsqq
ztvnnxbbdaupdovhhysicyycgtcbxesafdgbvfclvyhppucqpxtgzselbiclegbnzdxkdtiactwokenlczsiyuwabmmo
sbsgsopmjlyyftifyarbzvcrhokokxdmbxoinokqdfmrntxpqekeletghzzgouedwdn
etidolmmbhdzdytqzxrhgxbsafzvezdpbynvngfnhlpkyyyftjjsfpubhzuececqqbr
zaxwjbiqgczdzydmkdowsqwupvienlulymnnlrggcehhahvmoztosdbfqabnzinehwyvlnyksxbqoewqlsbldhuud
emjubuhzezzvzqcbjpfgsqhpzjafjdktbcvjryuysmbxeqyvreulvicoskbwzmfzwpzbyizcgluemeajscazrfwwa
cokghiewwqmdpvxztapjiyzwjgzewumvbzymoraehpudjwt
cdjdggfxbnqtuwezwwdybcmswgzrywutabzifummdtjokyv
hfcimgefrztckmwgfbo
bpxhbbdxfraapryauak
dhvdgaguettvvaoxarhpfrahecaekscqrigmari
dyzbzuaxcnyqwcgzhmyieuhardegrfjsyleiovx
mlmzshmtdfvtuzlcanspbyoduuyholqckv
jvpzjpgqceuvclhywpxbbjhzowzaicuaat
fbnhivqogbtwmnmqnioksacpxxnfnfrqyqxqtfinxpjlwomrmjhlrrzwwqhiavciwmfi
yahcadopeaokxblluwraldnsxyvnilwezbyemeftteznadtwxgubxazbvrwalzexztaj
yr
zb
zjqwtnufzspxjsztixv
mxwmyyuezmbzedazmeh
hcddxb
lbcdyb
ltmqzzsvfkqcuzybazsjdo
kiwvdzvxghnhlgtabpefda
jwqkgghxhmliapyqenypcqzidhdnmedvoqvzgfgilwklxisyeahipytrakazfwgiuhcn
vxaqueqzkthseqyosaetsxnozefsrvbqeqyicqphzzgjkedzaugqqufwuykzdrkgvscd
qvckzumufyhqpczunvmgiyajbiycftiyownjdjzbpfirgebvmrasqjaxmkdiftwgcfywvsumqsx
mwwxzmqcxzeuzcuswxncfuuebazmrlszcyabkekyxtfzuoexsynghzwtfhjhlgxebbjxfvwdtuz
tczphgcvehgttwericyyslc
iczzpyqyesmbyvxeibzzcza
jpwbmguwbjxjtgnayoknhudfqbxmfaqpplrnautvnmhqarubugukbeowfoeeiqmwcqdcwmplgbqnhpgfhgqvku
zzzamhzqqxyolfgdzdqyhybfkiyydxqutznmqdnxuncyfxtjzbtqaiaybpdssxfybibeahhgtbgfkhgukctdcy
congccvuikmlsknqttucgnlqxplwdokahjnvvegiwqtbfsjbvdiusdfwuroshonbepzlqjxmcsnevwq
bltmabqyolimzxilenbyfswxmdwzakhhotvxzacxjxzxfhkblwmonbsqcumqwtcbelzqozzhbjrpfha
nmheccfotxmzzhjtmiajedxnjxvjwnrbvxvedyfqpndblukjbjzobljrugixifjqkrcwbeemkkzpfjayiarutsa
nmgepaawwahuzelxfpmjakytqzwhyizxxjubszwxwyzbkyeoayzuxjzuvtlalklnexcyacixguzfejkzebsxizq
cejauhfyvfhstodagsluufidc
botsxofzzfewgnkslgthxafsb
txtuuolbgvieqyxdzyngkdaxuhgwzmgjjvylhavhtijfzvwdalxewsympoyvdhtlbchfgnexmmslcbrozsljw
kzuvintbfozeigycziemgcfoyyiwzhegeyqifgnmqifkzkygbpzbxubkuujpcveqycadbkjybwvgmaznxbhum
dzkepuqzoqepebgw
cbdejnoztlcdnbdi
epbdmokaouhekegpfjlhuywvgtbtozivvooplnnchlbkdvmr
usetuijsqwkribfrcjrguxyrvxmekykkfjvwkanxfjaxbxqo
punqanhwmitayqkdzqyhnieqosyrlidxxxcwlmolnvqopmr
bxpcxdbiyojszuhbcfyrqgqunueyrakuyymubqpcftvxzqp
qkdvjeiunidaalqfbkfbbaihaxjpxx
ybcwodfvbeguiyvjyhmpakixevhwzz
ugtbvmikzdueglpuksbbwoeopqygziitejdkhkkgyd
wbybejvwzzwdrayxgwbayweomwzdhvkscbkifgqtoc
oqznmyicoove
lzhzfydgfjoa
vfmrllvrsnjqiocbdrixjzgnrszghicnmvqjjtpcnhwgpdqlsyrcbckhocgboecvpczbepewpnpjatirudtcurrtlb
rkzskbzgwmksdvbagqeyhzaizxedhupyorlndwgucezsgdtclzgkabjoebmxojcojbwannnxprkdocwzgbvczztjra
vzrhgchcivnxhpuibmlmongbjheekvvxrvjtsonvjlxkihomxkbsyg
wzlytacapqyygwzqbprwmdnmezeaazxzefrzoxamfymhehfjynavzv
pwp
qfm
svmzxwahupklojcbqkfeblpht
ybhzzfkanuxehfvmgiwabgbek
fybokfthpftnrmdjyctofsnpuexcarwrpstrehbrzjnzvsoislrk
ynbsewwhsyyjxiwoznzmbzalwknaerzmrwxmsubpzagzeegavxmk
ebxji
aagyf
jzsfoasfxudbxenvj
qcxxvxoeyvljfruxq
wsuevxuydmolvatzpupybhtjfqtpcxkciwzqjverubkceqwefvyatrabcyrlpbv
ztsfocsmbuizduvzjtkzbzeeivmxxzmqgxeiuibpnslbntmfhwogvvnbacttyfo
rfdwukqwzmshqdzohdycpisqjaktzvzmhneqsocpinxzrsrcwdmdimbcrlcmvppxv
ucdawmgwzumebdtdrgzruetwhgxywyztafbrehwmvidmrsxbzicasfalvlnmxfslt
jxbnopxbfrmzvvpuxkjiflvqxxlcynhw
fcbjowyuacttixewmdndfkgvkmjnoqec
gtxehzhwr
eqbkhzary
hilyyuztrgjshdrbkjrfxenkrjtayurhakpbgmdowuzmprrgyyodvugyyufuitwiaczvv
drpzmybhzwikrrvzevxdpbvscgvqzytpjpmdcpnszyepykvfzvsrsxgzmkczhpookmzlx
tygrudzngiyrrvuhevzsvczkbxyoiuwbvbthbxlcfvfggzutbqttwuqavnpyubrhqhvdknfbqtmjlaokmopplx
xwpspdqjuastyeybpclyjczcsyzdmfzzxujbrrigckkvczscpsrvyuzozdybvquefnfrqqnmrzpljoxknwwssz
ruidqxjajuqybjbclldvqoiwbbriklhyizpiyychnmpftnonhoyqucxqmmggtebueollzzvzdihkjavinoiukzwwcwxa
nwuquybhqwkvalfbjwdtiubybbsgyueziezdziwtvhqjqbfkmmzyxodoojjfvmaybkzazzcwbejljrsavobvnzslzzzg
xr
zw
fuaprflszqlwyrnpplndvcdzhzkgbwztswbslhyytznmbvbnyzxsyivslwcdkflmofxfnwpg
fwwrsdmvzubgnzcwliwelablwwwfdxzizjburrpsagjgbybrrzyvzlvexxpuftgrlzzcqoif
buucpepotmhv
ajvctkskmscr
kubkoyyfcaxapvdgmtqntdiqnbzyogbrawxjncklsmbtviegafobtsznwdrbqfwuvuocaraeharbqusvhtwnwdplk
khaelxyoktzrqwaztdkwyzovsbzznqpxdzzrsnnldznkdieweaxakbnszccitrvwmzdhzwgprhjanowftziayxbtr
caaybaayglgobwbhjgryfgsglrgxeswdkfrzuovparpcaoksllnewddovzkfucmaqoavytejzijbppb
doezlbxzhlfmazwbaedzajkyhwqzcumcwfldrjqxjpdcdoamvaoejgxvnzlwvbpjeleuzuwhzefazrk
gbvveqyusyvuxvox
kjnxathzyzxgzsxz
yyfwcshoemfawdxbbrbtpyoxapiji
zcfnkueocffegakzbtqjazayzwowz
atgcgfkgyzxkzhilmwkbogyvdoemmgkkhpomxaoluupkbomvtwsvppwvjbqohcujufog
smhccopgszyzzfietrgevflbkcedvbcwjtucylzpyfayabryqiuxvpxoabupdcdctalc
njpbxoknuafilhcetwkmrrswjyqyklzpetgngdycfauacoqscflqzruffxncodapyulmxeslethmkgzqy
weoayhtgyoblcobelvgzvbgksmnvjulvbwgsbczavpwvdovcraxhtkdcjoncebtysyekyenqrffdpjzhj
aemmubdtbeomjhfphushtiqynzosswjeuvqzebeuresaqirrfwblprztfhkuyufwgvfzspvxhegbqkzhmowiwfdbcbjpbdujz
ucepkaboadzhkkhwuuciodyzzhrxzigdnfutabxxhbzmwghhgzirugzrokhwpbejlmfzimyyffdcmzdgsgpdxrducarhegnac
ckfzphlxssgzjfoyxydvadirjzdxjgoxhxanyckoooruhnimtcsmvmd
bhbzslmykjbzoosyqsixhoijaluxttuccuctzaqdehzvhupxfrxqwas
kudcqlhwc
diddihqbs
rtignxmfsyulcrojpxlgkmylfolirxehxfkvwadegerqbmye
pagepzljtzwrrgmirvkyppzpfflsfbkdyvciwlzbsdkkaiwb
zbqskpxvwjriiqqmhqhkjisksmihttcupfzyylrvsfrtcopvlkcrqghvwelkrqqrffuygsggrbsu
oafnnryocoyrhyyjfoufcafyhlibxacvlayghthafcdeefyeeqdvbyhcffinvhuvfwyxtylmqauw
hpckbpeoeqyrmmdzafgtshitmibbpoucyynengtaaixahewgvpsiufqxgilmta
uymbrhyydbrwlbdzgfdvzhavpdsbzlbbpkxandxyhglxhruoizgpvazylamzgp
nhuelbqrlnbzlxahpsmgwpiflujdazsq
wbfcearbocgzcsebshcmxdaqjinzujwj
swpogxvmefzfckgpwadkxzaqktvhzegtqlgxkfynowfmllyjigzldltvwfxseifqqishhuoguviviuvpkfljauaqtmynjwleevsd
sxtocrmzerzefkdnzpcoqfduhxzfzojayfcjvxmtfjdipkxytcugcbhyvdcvdbfzfonigzwgduyjezzkhcfdfcoiyoxmizebdbab
jytmjgjwylwpjvixougyggjmbzarudlmlyhvcxbhuqurxlznwkkrjbyiioumtsmybrtzvibqyvhibxmvgkoiyzmjdrqvyygzf
yybcduhzlozvfbbkrjvpwvwybzodlasiwzdxpzbjvcaszrzixsrjdmziggsacyvpaiwzxvliryooiuoyecvbzpflbuezzzace
fkjppidojlqgncxyjyhyxnyidgsginlaaupkdlwhrwcddbnjbstblfkokauobwqquuuybmdznuvqzdvzlmndejmhmot
yrzfbabyzvxszlyzdfndyxzgcfwviosvltirtozftxkcpapgpvvbdgazcwyyayvfxeyzxwahhlwtzaiiwhqcsjiifpp
pmuhnplxohaqyfufofshdbmuqbwgkeswgvxesmcyeovixplrwrhwbfzlireqzxkcqpehhgxlhtztwk
kpweoifuudyzzasxdshnsafcgdobnjlzcwzawtazcpysbgabbrrnkfbzavdrzzmvrvgcqugsfrzubb
qrijtwrfphfawjridbsxfqalzurcttsstalqeqaqfnmyoanqccafzkqmjfwhaoaugyhqvesbctjgcjdkpcbtarznaf
ztvevkyzjwpmfgqdsaxzrbsgzsenuxtqzyfbgwxcaizqxtexpjqbzauhpnyclbetejfdgbdybvbaoxcibialwvzjzk
cclsuzqlpozlyuczouxnbmgxrjbkhvmxampnjogumsicezahpkkcjvefaqgqxqbizpdikjiluyhvrzgtocrsywvimeredkudj
eckfgetewmpqzfavuzymbkggtgtshydukadvwsdxfbvsktkzmcoaccgchuexcgbnzgojbjhuqzhwjpyzdaebzawuqbzwdotmc
ffpnxkftyeiruxvuamzriufr
fcnbyldezeltasxvmyqrgych
rlzzbgfkjtodafywrlgfiyfdgmrnjgcjpqohtxbik
erzzalacizptnphaiefdgzasdkezdrclszvjvkmkg
adesjdbibztppbggxblilqhkkpbsuzeesguhw
dbszqkagbvvrjokfzoqabfscnzauzzydvqmht
dlynhdaodktptgdqayyrjngknutgfxzzfbpndfavsbcosnlgqblpzyclfyzmhwcqirsbsneyq
bdzhsanvsrzgujdrxzzzttexzzrkxyzjaaxdkgzxeabkctadqabqznrazdzmbyciltbwgewzc
ctiqjyoyptinnhaldxfvvtzweqweoftatanmkqzptsjaxaacxewhwpgdcidgxejekere
gxdoizszuzyzyqwgwzdzrxczxmyddxiiqwevfhvdzvencjkkzeifykadczbfzhkgbuya
fayescgghapkhsenmqvpgmiquj
lblcfqaoafglbanhgxspclrzvb
wmynwsjqvobkfsgskmiotzermh
wsznajjkwbatehekkixlhzancm
manptwegwdkupnycklgcgtnzdzsnreqmnnopthtnshvcaklhiunkvflhgswepffevhrbymlkpzrllxzxh
hryevndfotjvxgziemcbarkxzxvatdygaoabnsgjtfxavlciazrktyzpktydfxcmyvagifgwryeluyynl
rupymrmljjopyxyojipyhkgvqrrnjdrbkmvpdzcdokjmclgpccolykvjdymzbgyvoxp
whebbdbqmcwgmyeflifrvdewoqzcnnsxxlqvdvpasnagboescwzjlznzcyuzszzztrb
gphzuanjvfexk
ozlznuwpzmmgy
qtupenralndepnkduorniaolajkxemkrpwckqmbrzaqopyvehszxxzdykdguehvliuebnjjincqxa
suwbbdotlqucsevgvruqncmqsewhgbqqgxutvvltzqlyiqtkcgvykmqzflayamwtdibtmondeaazc
rjkgxqkfptnygqubnhlqwiaqlsdhbxpvjtbprvmwmyuqmrqxlbijrogagzvsjfpsijtzxlujvyusrojqqscekyjykeahqj
umivzjvurffkczsbwayjzsfyyodjawzvfnqefjnxruwtluniiedfvrreczpwfcczcwvfyjvvxjvqtnbeqxwoczxznctnlh
titzqbalmdglfbdsauqypyyzvayrhoufimddbsdrkhqgooekbndhdwke
pbuczbouuagkibcxrzlxwacoyezbdvkecgdjkxafzfyaltjaaxgwwxpv
gipvcefrhkuiecqyeuernaeevzazkgkokspcsxyyzhhocyvtjxtzzhmbj
tazvadsladfuebnzeyasyrdwdzfzfdiipyxcxzrczbgtznzxzcwecurbj
glxklcwfvpkaxkvkjvumcgqxwkoupsmqxudzqasugugqgkcbgvjfftjauyzexivbharjcctjwhoexoxmddcuaaqjcitosuydksz
enyhdbqexzurtedcdsrwbhqnvjrrjtwmzuxzszvkpzmtowwbarfbdxgehzzdzpgrygmicbyrexppzoybbbjrnrmocfymuwjdcsz
ojebijjzhdxskvxecuyjtzjixpkknoabwxjbmuneqjwdunpvmdpdyzvcsnojwuhrtixaiejyzoeujw
rebfactzcsrjrzzctvmkjzogzoovvbybygbrvvgqtsxcqqtpoxmdzzxgbhicwyhzerxvexzzxlbzpe
xwretlqsfjquvnankkyojwwijtqjvcbtvqdpc
pyojijtycjrvgwvmdusenwzbfutbfcmxvptma
kuyrqzavgudrjesgux
tozyqyjvimyznbfeay
btsmfrivanpfjiwvfxplhizwhkgobzzilypvggnfykpazorwnigrkfosjfwunggbcugzflnyhvgaolqszbjqtqw
fqfteasktxsluiztfiwlmczyrathqrzonzswzsyayudzussxomykqcrmdrxyocdbbyczhgkkrwcdcvvksgmkzrx
eceqdhegpimluqdkwsagwyzgiqfczvpdawevmzxjivtbd
ocppbhjgbnznxwctitffszpydutczadddyygzuzhfwxaa
svihfxsubnrbqjwktrwxgawmrmdvzqbvztvtqnlsagloayevmspmdkatgdjboearrvoucf
rtfeyhvpbmobymrtfbvydyynlhpbnuezucvvhpujhewtnlaxrevhpvvwrdcbredvdhgxcb
lzkqvfspykeuvbqcvvlsjpjogycvttegpijsutbqdfljexgaismnlomewmgobxjiibvsygmohrwhierxk
ypczjwgwzwbdzsgcpytwtqvdrwfymksbxaqjrvkwtayiphequnkqdjxegznpazkjrajqtdhxcwygdcfye
dckaggxlqamjipewbtmppargdqvioefphdseuurkgjnnnufz
lplgvxzutzpmiukiuwiwopyibeqjzsauudmcoztaobjnlctm`

	scan := bufio.NewScanner(strings.NewReader(testcasesRaw))
	scan.Split(bufio.ScanWords)
	if !scan.Scan() {
		fmt.Println("invalid test file")
		os.Exit(1)
	}
	t, _ := strconv.Atoi(scan.Text())
	for i := 0; i < t; i++ {
		if !scan.Scan() {
			fmt.Println("bad test file")
			os.Exit(1)
		}
		x := scan.Text()
		if !scan.Scan() {
			fmt.Println("bad test file")
			os.Exit(1)
		}
		y := scan.Text()
		input := fmt.Sprintf("%s\n%s\n", x, y)
		exp := expected(x, y) + "\n"
		if err := runCase(exe, input, exp); err != nil {
			fmt.Printf("case %d failed: %v\ninput:%s", i+1, err, input)
			os.Exit(1)
		}
	}
	fmt.Println("All tests passed")
}
