package main

import (
	"bufio"
	"bytes"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strconv"
	"strings"
)

func buildOracle() (string, error) {
	dir, err := os.Getwd()
	if err != nil {
		return "", err
	}
	oracle := filepath.Join(dir, "oracleB")
	cmd := exec.Command("go", "build", "-o", oracle, "585B.go")
	if out, err := cmd.CombinedOutput(); err != nil {
		return "", fmt.Errorf("build oracle failed: %v\n%s", err, out)
	}
	return oracle, nil
}

const testcasesBRaw = `9 2 .......AB .....B.B. sA....BBB
6 1 s..A.A ..AA.. ..AAA.
9 2 ......... ......... s........
7 2 .....AA ...A..B s......
10 1 .......... s....AA... ...AAA....
11 3 sBBBC...... ....BBB.... ......C.C..
6 3 sAA.C. ....BB ...CCC
6 1 ...... s..... .AAAA.
9 3 s..BBB.AA ......... ........B
10 3 .B......BB s......A.. ..A.......
8 1 s.....AA .......A .......A
10 2 .......... s.AAA.AA.. ...B......
6 1 .....A s..... ......
12 1 ........A.A. ............ s...........
7 3 ..B.... s...... .......
9 2 .B.....A. s..A..A.. .........
6 1 ..A.A. ...AAA sAA..A
6 2 ...... s.BB.. ......
11 2 .....BAAA.. sBB.....AAA ..AAA......
7 3 ....... s...BBB .......
11 2 ...B....... ...BB...... s.....B....
11 3 s.......... ..........B .BB........
10 2 s...BBB... .......... ..........
6 3 ...... s..... ....BB
6 3 .BBB.A ...... s.....
7 1 s...... ....A.A ...AA.A
8 3 ......AA ......CC s...B...
9 2 .......AA ..AAA.... s.BBBB...
6 1 s..... ....AA ......
11 2 ...A.BBB... sA.....AAA. .......BBB.
6 3 s...C. ...... .....B
8 1 ....A... ....AAA. s.AA....
10 2 s..BBB.... .......... ..........
9 2 ..BBB.... ..B...... s........
8 1 s....AAA ........ ........
12 2 ........ABB. ...........A s...........
7 2 .B..... s..AAA. .......
8 3 ........ s..AAA.. ....CCBB
7 1 ....AAA s..AAA. ...AAA.
9 2 s.....A.. ..B...B.. ........A
11 2 ....BB..... .AAA..BB... s..........
12 2 s...BB.A.... ............ ............
7 3 ....... s...... .......
6 2 ...... ...... s.....
12 3 ............ ............ s...AA....BB
6 3 s..... ...... ....AA
9 1 ......... sAA...AAA ..AAA....
8 1 ........ ..AAAA.. s.......
9 3 ......... ........B s........
9 3 ......... s......AA ....BBAAA
9 2 sBBB..... .......A. ........A
7 2 ....AAA sAAA.AA .......
7 2 s.BBB.. ..BBB.. ..B....
6 2 ...A.B ...... s....A
10 2 s......... ......AAA. ..........
6 1 s..... .....A .AAAAA
9 3 s........ ......CCC ........C
8 2 s....... ........ ........
12 1 .........AAA sAAA........ ..A.........
10 3 .C.......C s......CC. ..C.....AA
7 2 .AA.... ....... s...BB.
6 3 ....B. s..AAA ......
7 2 ....BBB ......A s......
9 3 ......... ......... s........
6 3 ...... s..... ...BB.
8 3 ........ .....CCA s.......
7 2 sBBAA.. ....... .AAA...
12 3 s........A.. .........C.. ............
7 3 ....... .....C. s..AA.B
10 1 s..AA..... .AAA..AAA. .AAA......
12 1 s.AAAA...... .......AAAA. .....A......
11 2 .AA..A..... ....A.BB... sBBB.......
9 2 ......... ........B sA.....B.
11 2 ........... s.......... ...........
8 1 s....... .......A .AAAA...
9 2 ...BA.... s........ ...B.....
10 1 s......... ...AAA.... .AAA.....A
12 1 s......A.... ............ .........AAA
6 1 sAAAA. ...AAA ....AA
11 1 s...A....A. ...AAA..... ...........
10 1 .....AAA.. s......... ....AAA...
8 2 ....B... s..BBBB. ...AAA..
8 3 s......C ....BBB. .....AAA
12 3 s.AA........ ............ ...C.A......
7 3 .AAA... s..ACC. .CC....
9 1 ......... ......... s........
10 3 ....BBB... s......... ...B......
11 1 .A.....AAA. ...A.AA.... sAAA......A
7 2 ...BBB. ....AB. s...BBA
10 2 s.AAA...B. ..BBBAA... .A.......A
12 1 s.......AA.. ...AAA...... ....A......A
6 1 .....A .....A s.AAAA
10 1 s...AAA... .A...A.... ..........
12 3 s........... ......A..... ..AAA.......
8 1 ......AA s....AAA ........
8 2 ....BBB. s.A.BBB. ........
6 1 s..... .....A ...AAA
11 3 ......CCC.. s...CC..CCC ...........
11 2 .AAA....... s......AA.. .........AB
6 2 s...BB ..B... ...AAA
`

func main() {
	if len(os.Args) != 2 {
		fmt.Println("usage: go run verifierB.go /path/to/binary")
		os.Exit(1)
	}
	bin := os.Args[1]
	oracle, err := buildOracle()
	if err != nil {
		fmt.Fprintf(os.Stderr, "%v\n", err)
		os.Exit(1)
	}
	defer os.Remove(oracle)

	scanner := bufio.NewScanner(strings.NewReader(testcasesBRaw))
	idx := 0
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if line == "" {
			continue
		}
		idx++
		fields := strings.Fields(line)
		if len(fields) != 5 {
			fmt.Printf("test %d: invalid line\n", idx)
			os.Exit(1)
		}
		n, _ := strconv.Atoi(fields[0])
		k, _ := strconv.Atoi(fields[1])
		input := fmt.Sprintf("1\n%d %d\n%s\n%s\n%s\n", n, k, fields[2], fields[3], fields[4])

		// run oracle
		cmdO := exec.Command(oracle)
		cmdO.Stdin = strings.NewReader(input)
		var outO bytes.Buffer
		cmdO.Stdout = &outO
		if err := cmdO.Run(); err != nil {
			fmt.Fprintf(os.Stderr, "oracle run error: %v\n", err)
			os.Exit(1)
		}
		expected := strings.TrimSpace(outO.String())

		// run candidate
		cmd := exec.Command(bin)
		cmd.Stdin = strings.NewReader(input)
		var out bytes.Buffer
		var stderr bytes.Buffer
		cmd.Stdout = &out
		cmd.Stderr = &stderr
		err := cmd.Run()
		if err != nil {
			fmt.Printf("test %d: runtime error: %v\nstderr: %s\n", idx, err, stderr.String())
			os.Exit(1)
		}
		got := strings.TrimSpace(out.String())
		if strings.ToUpper(got) != strings.ToUpper(expected) {
			fmt.Printf("test %d failed. Expected %s got %s\n", idx, expected, got)
			os.Exit(1)
		}
	}
	if err := scanner.Err(); err != nil {
		fmt.Fprintf(os.Stderr, "scanner error: %v\n", err)
		os.Exit(1)
	}
	fmt.Printf("All %d tests passed\n", idx)
}
