/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author
 */

#include <iostream>
#include <fstream>

#include <iostream>
#include <vector>

using namespace std;

class ADoggoRecoloring {
public:
	void solve(std::istream& in, std::ostream& out) {
		int n; in >> n;
		if (n == 1) {
			out << "Yes" << endl;
			return;
		}
		const int B = 128;
		int visited[B];
		for (int i = 0; i < B; ++i) visited[i] = false;
		char c;
		for (int i = 0; i < n; ++i) {
			in >> c;
			if (visited[c]) {
				out << "Yes" << endl;
				return;
			}
			visited[c] = true;
		}
		out << "No" << endl;
	}
};


int main() {
	ADoggoRecoloring solver;
	std::istream& in(std::cin);
	std::ostream& out(std::cout);
	solver.solve(in, out);
	return 0;
}