package main

import (
	"bufio"
	"bytes"
	"fmt"
	"os"
	"os/exec"
	"strings"
)

// Embedded testcases from testcasesA.txt.
const embeddedTestcasesA = `100
25 GRGBGGGGGBRBRGRRBGBBBRGRB
5 BGGBR
23 GGBBRBGGBGRBRRBGBBBRBGG
16 BGBRRBRRRBGRRGBG
7 GBGBRBG
35 RBBBGGRBGGBRGRRRRBBGGRRBRRRRBBBGBBG
34 RRBBGBGGGBBBGRGBRGBBGRRRBGRBRGRGGR
7 RBRRBBB
39 BRRRBRBBRGRGRRBRRRBRGRBRBRBGBRGRRRBGGGR
4 BGRB
7 BGRGGBG
37 RBBRRBRRGBGRBGBRRGBGBBGBGGBGRBBRGBRGB
3 BGR
16 GGBGBGBBBRBGGBGB
6 RBRBGR
16 RBGGBBBGRGBBGBBR
11 GRGBRGBGBBR
3 GGG
30 RGRBBRBRRGBGGRRRBRBBBRRRBBRGGB
12 RGGBRRGGRGRB
34 BBGRRGRRRRBGBGGBRBBBBGBBGBGGBRRGBG
1 R
10 GGGGBRGBRR
18 RRBGGGBRGRGBRRGRBB
5 GGGGG
7 RBGGGGR
31 RBGGRGGBBRRBBGBRRRRBRRGRRGBBGGG
38 BBRGRGRGBRGRGRRBRBGBRRGGGRBRRBRRRGGGBR
7 BGRBGBB
28 BGBGGGBBRBBRRGBBGGRBRGBRGBGB
46 GRRBRRRRRGRGGRRBGGBGBBRBRBBBRBGRGBBGGGBBRRBRBR
20 BBGGRGGGGGGRRBRRGBGR
3 GGR
32 BBRBBRGGRBGGGRRGRRRBBRBGRBBBGRGG
8 RBBGBBGB
8 BBBGRGGB
44 RBRRGGGRGGBRRRGGRBBBBRRRBBBBGBGRRGBGRRGRRGRB
2 GG
44 GRGGBGRGRRGBRGGRRRGRBRRRRBBBRBRGGBRBRRRGRGGB
17 RRRGGGGGBBGRBRRBB
20 RGRRRGBRRRGGGBRRBRGR
45 RRGGBGBRBGGBGRRGBGBBRGGRGBGGRGGGRRRGRBBBRBGGR
50 GGRRGGBRGGBBRGRGRBGBGRRGRBGBBRGBGRBGRBGGBRRGBRR
38 BGGRBGGGBRBRRRGGBGRBRRRGGGBRBBBRBRGBBG
48 GGGGBBRRRBRGGBGRBBGGBGBGRGGBBGGBRGGRBGRBRRGGGRBR
44 RBBBGRGRRBRGBBGBRRBGRRGGBGGRGGBBGRGBRBGRRRGG
25 GGGBRRGRBBRGRRBRRGRBBBRRB
20 BRBBGGGGRBBBBBBBGBGG
17 BGRGGRRRRGRGBRRRG
44 RBGBRGRGBRBRGGBGGGRBRRGRRBGRRGBBBGGBGGGGBRRG
36 RRGGBGRGGGGRRRRRRGRGBRGBGRRRGRRGGGGR
36 GBBRBGGBBGBBGGRRRBBRRBGRRGBBRBBBGRRG
42 GRBBGRBBBBBGRBRRBGBGRGBGGBRRRBBGGBBRRGRRBR
9 RGBBRRBRR
49 GGBBRBGRBRBBGGGGRRBBRBGBGBGBRGRBGBRGGGRRRGBBRGG
43 BRGGBRGRGBBRBBRGRGBRRRRRRBGRRGBGRRGGRGGRBGB
48 GGRGGBBBBBGRBRGGRRBRBBBBBRRGRRRRRBBBRBRGBRBBGBR
39 RGGBBGRBRGRGGBRGRBGRBGGGGGRGBGBGRBBBGBR
30 GBRGGGRRGBRGBBBBGBRBBGGGRRBGRB
44 BBBGRRGBRBRBRGGGBGGGGBGRRRBRGRGRBGBBGBBRRBGG
12 BRRBBRBRBBBB
25 GGGGRGBGGBBBGGRBGRRBRBBBG
24 GRBGBBRRGBRBRBGBBGRBBRBR
18 RGRBGRBBGBBRRRGRGB
26 GGGGBGRGRGRGRGGGBBBGBRBGGB
9 BBGGRGGBR
3 RBG
24 RRRBRBBGRGRGGRBGGBRBRGGB
4 RRRG
46 BBBRBBRBBBBBGRGBRRBRGRGGBBGGBGRGBRRBBRBBRGRRBG
40 RGBRBGBRGBRBRBGRRRGBGBGGGBGBRRGRRBRRGBRR
27 BRBGGRBBRGRGRGGBBGBGBGGRRGG
13 GRGRRRGRRGBBB
1 G
30 BBBGGRRBGGRBBRRGGRGRRBBGRRGGRB
45 RRRRBBRBGRGBBGRRRBGGRRGRRGGGBRGBRRBRBGBRRRRGB
1 R
4 RBBR
50 RBGRGGBBGBRRGBRBGRRGBBGRGGRGGRGRBGGBRGGBGBRBBGRGRB
21 GBRBRRBGRGBGGRBGBGRRG
31 GRBGBRGGRBGGBBRRGRBBGGGBRGBGRBG
18 GBRGRRRBGRRGBGGRBB
46 BRGBBBRRRRRRRBRGGBBGBGBRGGRGBBGBBRGBBBGRGGGGBG
27 GRBRRRBBBBBRBBBRBBBBRGBBBRG
6 RRRGBG
21 RBGGBBGBGRRBBRBRRBRBG
39 BRGBBGGRBRGRGBRGRBBGGRBGRGBRGBGBBGGGRRB
24 RGBRGRRGGBGBRGGRRGRGRRBR
43 RBBRRRGBBBGBBRGBGGRBRRRGGGRRGGBGRRGBGRBGGRR
19 RBGBGGGBRRGGBGRBBGB
23 GGGGBGRGGRGRGRBRGGRRBGG
30 BGBBRBGBGGRGBBRRGGGRGRBRGRGRBG
12 RRBGRRRRGBRR
8 BBRRBGRR
34 BGRBRRRGGGRGRGRBGRBGBGGBGBRBBRGRBR
18 RBRBBRGRBBGRGBBRBR
45 GRBGGRGBGRGGGRBBGRGRGGGRGBRBGGRGRGGGRRGGGBGBR
34 BRRGBBBRRRGRGBRGGBRGGRRGRGBBRBGRBB
46 BBGRBBBGBBRBGRRGBGBBRRRRRRGBBRBBRBGBBGBGGBRRGB
23 BGGGBGGRRRRRGGBBRGBRRGR`
func run(bin, input string) (string, error) {
	var cmd *exec.Cmd
	if strings.HasSuffix(bin, ".go") {
		cmd = exec.Command("go", "run", bin)
	} else {
		cmd = exec.Command(bin)
	}
	cmd.Stdin = strings.NewReader(input)
	var out bytes.Buffer
	var stderr bytes.Buffer
	cmd.Stdout = &out
	cmd.Stderr = &stderr
	if err := cmd.Run(); err != nil {
		return "", fmt.Errorf("runtime error: %v\n%s", err, stderr.String())
	}
	return strings.TrimSpace(out.String()), nil
}

func expected(n int, s string) string {
	cnt := 0
	for i := 1; i < len(s); i++ {
		if s[i] == s[i-1] {
			cnt++
		}
	}
	return fmt.Sprintf("%d", cnt)
}

func main() {
	if len(os.Args) != 2 {
		fmt.Fprintln(os.Stderr, "usage: go run verifierA.go /path/to/binary")
		os.Exit(1)
	}
	bin := os.Args[1]
	scanner := bufio.NewScanner(strings.NewReader(embeddedTestcasesA))
	scanner.Scan()
	tline := strings.TrimSpace(scanner.Text())
	var t int
	fmt.Sscan(tline, &t)
	for i := 0; i < t; i++ {
		if !scanner.Scan() {
			fmt.Fprintf(os.Stderr, "not enough test cases")
			os.Exit(1)
		}
		line := scanner.Text()
		var n int
		var s string
		fmt.Sscan(line, &n, &s)
		input := fmt.Sprintf("%d\n%s\n", n, s)
		want := expected(n, s)
		got, err := run(bin, input)
		if err != nil {
			fmt.Fprintf(os.Stderr, "case %d failed: %v\n", i+1, err)
			os.Exit(1)
		}
		if strings.TrimSpace(got) != want {
			fmt.Fprintf(os.Stderr, "case %d failed: expected %s got %s\n", i+1, want, got)
			os.Exit(1)
		}
	}
	if scanner.Err() != nil {
		fmt.Fprintf(os.Stderr, "scanner error: %v\n", scanner.Err())
		os.Exit(1)
	}
	fmt.Printf("All %d tests passed\n", t)
}
